const	
	PLAYER = 0;
	ATTACK_TIME = 6450;
	
{.$DEFINE DebugDialog}
{.$DEFINE DebugHero}
{$DEFINE DebugGameSpeed}
{$I KD_CustomPanel.script} //custom panel 
{$I KD_Dialog.script}
{$I KD_Heroes.script}
{.$I KD_SaveDefPos.script}
{.$I KD_GatherResources.script}

var AttackDefeated : Boolean;
	Dyron : record//guest, not Dyron
		ID, GroupID, AttackTime : integer;
		KineticPos : TKMPoint;
		KineticTime, KineticRadius : Integer;
	end;
	DialogEnd, Recruit, Malcolm, Eryt : Integer;
	DialogSet, AllianceChanged : Boolean;
	
	



Procedure KillNotAllied(aUnit : Integer);
begin
	If aUnit <= 0 then 
		Exit;
	If S.UnitOwner(aUnit) in [1, 2] then 
		Exit;
	A.UnitKill(aUnit, false);
	
end;

procedure AddHouseDamage(aHouse, aDamage : Integer);
begin
	If aHouse <= 0 then
		Exit;
	A.HouseAddDamage(aHouse, aDamage);
end;

procedure DoKineticExplosion;
var aX ,aY, aRadius : integer;
begin
	aRadius := Dyron.KineticRadius;	
				
	for aX := Dyron.KineticPos.X - aRadius to Dyron.KineticPos.X + aRadius do
		for aY := Dyron.KineticPos.Y - aRadius to Dyron.KineticPos.Y + aRadius do
		begin
			KillNotAllied(S.UnitAt(aX,aY));
			AddHouseDamage(S.HouseAt(aX,aY), 50);
		end;

end;

procedure KineticExplosion(aPos : TKMPoint);
var aX ,aY, aRadius : integer;
	aRandom : Single;
begin
	aRandom := S.KamRandom; 
	If aRandom < 0.05 then 
		aRadius := 6
	else
	If aRandom < 0.3 then 
		aRadius := 4
	else
		aRadius := 2;
		
	case aRadius of 
		1: A.SpecialAnimAddFront(aPos.X, aPos.Y, [1501, 1502, 1503, 1504, 1505], 1);
		2: A.SpecialAnimAddFront(aPos.X, aPos.Y, [1496, 1497, 1498, 1499, 1500], 1);
		4: A.SpecialAnimAddFront(aPos.X, aPos.Y, [1491, 1492, 1493, 1494, 1495], 1);		
	end;
	
	Dyron.KineticPos := aPos;
	Dyron.KineticTime := S.GameTime;	
	Dyron.KineticRadius := aRadius;		
end;

Procedure OnUnitHit(aUnit,aAttacker : integer);
begin
	If aAttacker = Dyron.ID then 
	begin
		if S.GameTime >= Dyron.KineticTime then
			KineticExplosion(S.UnitPosition({Dyron.ID}aUnit));
	end;
end;

procedure OnHouseDamaged(aHouse, aAttacker : Integer);
begin
	If aAttacker = Dyron.ID then 
	begin
		A.HouseAddDamage(aHouse, 300);
		//A.SpecialAnimAddFront(S.UnitPositionX(aAttacker), S.UnitPositionY(aAttacker), [1491, 1492, 1493, 1494, 1495], 1);		
		KineticExplosion(S.UnitPosition(aAttacker));
	end;
end;

procedure OnTick;
var GT : Cardinal;
begin
	GT := S.GameTime;	
	If GT = 150 then 		
		A.GroupOrderWalk(Eryt, 89, 112, 7);
	If GT mod 100 = 0 then 
	begin
		A.GroupOrderWalk(Dyron.GroupID, 64, 107, 2);
		If GT >= 1000 then 
		begin
			A.GroupOrderWalk(Malcolm, 66, 107, 6);
			A.GroupOrderWalk(Eryt, 66, 108, 6);
		end;
	end;
	
	If not DialogSet then
	begin
		If GT mod 10 = 0 then 
		begin
			If not AllianceChanged then 
				If Unit_IsCloseTo(Dyron.ID, 19, 106, 7) or Unit_IsCloseTo(Dyron.ID, 141, 103, 7) then 
				begin
					A.PlayerAllianceChange(0, 2, true, true);
					A.PlayerAllianceChange(1, 2, true, true);
					AllianceChanged := true;
				end;
			If S.UnitAt(64, 107) = Dyron.ID then 
			begin
				DialogSet := true;	
				Dialog_SetStartTime(10);
				Dialog_Loc(65, 107);
				Dialog_Add(57, 30, Dyron.ID);
				Dialog_Add(58, 20, S.GroupMember(Malcolm, 0));
				Dialog_Add(59, 35, Dyron.ID);
				Dialog_Add(60, 40, S.GroupMember(Malcolm, 0));
				Dialog_Add(61, 50, Dyron.ID);
				Dialog_Add(62, 55, Dyron.ID);
				Dialog_SetEndMsg(64);
				DialogEnd := Dialog_EndTime;
			end;
		end;
		If GT mod 300 = 0 then 
			A.PlayWAV(PLAYER, 'StoreBell', 0.5);
	end;
	If GT = DialogEnd then
		A.PlayerWin([0], true);
	//dyron effect
	If Dyron.KineticTime > 0 then 
		If GT = Dyron.KineticTime + 4 - (Dyron.KineticRadius div 2) then 
			DoKineticExplosion;
end;

procedure OnMissionStart;
begin
	gPanelsRefreshRate := 10;
	//heroes setup
	Recruit := S.UnitAt(83, 111);
	Malcolm := S.GroupAt(94, 111);
	Eryt := S.GroupAt(103, 111);	
	
	A.UnitDirectionSet(Recruit, 2);
		
	//dialog setup	
	gDialog.Player := 0;
	A.CinematicStart(PLAYER);
	OverlayDialogSetup;	
	Dialog_SetStartTime(10);
	Dialog_Loc(91, 111);
	Dialog_Add(50, 30, Recruit);
	Dialog_Add(51, 20, S.GroupMember(Malcolm, 0));
	Dialog_Add(52, 35, Recruit);
	Dialog_Add(53, 40, S.GroupMember(Malcolm, 0));
	Dialog_Add(54, 50, Recruit);
	Dialog_Add(55, 55, S.GroupMember(Malcolm, 0));
	Dialog_Add(56, 20, S.GroupMember(Eryt, 0));
	Dialog_SetEndMsg(63);
	
	Dyron.GroupID := S.GroupAt(104, 25);
	Dyron.ID := S.GroupMember(Dyron.GroupID, 0);
	A.GroupMakeHero(Dyron.GroupID, true);
	Unit_SetStats(Dyron.ID, 200, 1200, 1000, 100, 30, 8, 10, 10);
	A.UnitHPSetInvulnerable(Dyron.ID, true);
	
	A.UnitOrderWalk(Recruit, 87, 111);
	A.GroupOrderWalk(Malcolm, 89, 111, 6);
end;