const	
	PLAYER = 0;
{.$DEFINE DebugDialog}
{.$DEFINE DebugHero}
{$DEFINE DebugGameSpeed}
{$I KD_CustomPanel.script} //custom panel 
{$I KD_Dialog.script}
{$I KD_Heroes.script}
{.$I KD_SaveDefPos.script}
{.$I KD_GatherResources.script}
{.$I KD_Events.script}

var DialogEnd : Integer;
	Guest : record//guest
		ID, GroupID, AttackTime : integer;
		KineticPos : TKMPoint;
		KineticTime, KineticRadius : Integer;
		Spawned : Cardinal;
	end;

//kinetic effect begin
Procedure KillNotAllied(aUnit : Integer);
begin
	If aUnit <= 0 then 
		Exit;
	If S.UnitOwner(aUnit) in [1] then 
		Exit;
	A.UnitKill(aUnit, false);
	
end;

procedure DamageHouse(aHouse, aAmount : Integer);
begin
	If aHouse <= 0 then 
		Exit;
	A.HouseAddDamage(aHouse, aAmount)
end;

procedure DoKineticExplosion;
var aX ,aY, aRadius : integer;
begin
	aRadius := Guest.KineticRadius;	
				
	for aX := Guest.KineticPos.X - aRadius to Guest.KineticPos.X + aRadius do
		for aY := Guest.KineticPos.Y - aRadius to Guest.KineticPos.Y + aRadius do
		begin
			KillNotAllied(S.UnitAt(aX,aY));
			DamageHouse(S.HouseAt(aX,aY), 50);
		end;

end;

procedure KineticExplosion(aPos : TKMPoint);
var aX ,aY, aRadius : integer;
	aRandom : Single;
begin
	aRandom := S.KamRandom; 
	If aRandom < 0.05 then 
		aRadius := 4
	else
	If aRandom < 0.3 then 
		aRadius := 2
	else
		aRadius := 1;
		
	case aRadius of 
		1: A.SpecialAnimAddFront(aPos.X, aPos.Y, [1501, 1502, 1503, 1504, 1505], 1);
		2: A.SpecialAnimAddFront(aPos.X, aPos.Y, [1496, 1497, 1498, 1499, 1500], 1);
		4: A.SpecialAnimAddFront(aPos.X, aPos.Y, [1491, 1492, 1493, 1494, 1495], 1);		
	end;
	
	Guest.KineticPos := aPos;
	Guest.KineticTime := S.GameTime;	
	Guest.KineticRadius := aRadius;		
end;

Procedure OnUnitHit(aUnit,aAttacker : integer);
begin
	If aAttacker = Guest.ID then 
	begin
		if S.GameTime >= Guest.KineticTime then
			KineticExplosion(S.UnitPosition({Guest.ID}aUnit));
	end;
end;

procedure OnHouseDamaged(aHouse, aAttacker : Integer);
begin
	If aAttacker = Guest.ID then 
	begin
		A.HouseAddDamage(aHouse, 400);
		//A.SpecialAnimAddFront(S.UnitPositionX(aAttacker), S.UnitPositionY(aAttacker), [1491, 1492, 1493, 1494, 1495], 1);		
		KineticExplosion(S.UnitPosition(aAttacker));
	end;
end;
///kinetic effect end

	
	
const MAX_DEFENCE_POSITION = 72;
procedure AddGroup(aOwner : Integer; var aLast : Integer; aUnitType, aCount : Integer);
var C : Integer;
	DP : TKMDefencePositionInfo;
begin
	While (aCount > 0) and (aLast <= MAX_DEFENCE_POSITION) do 
	begin
		DP := S.AIDefencePositionGetByIndex(0, aLast);
		C := U.MinI(aCount, 12);//max 12 units
		aCount := aCount - C;
		A.GiveGroup(aOwner, aUnitType, DP.X, DP.Y, byte(DP.Dir) - 1, C, 4);
		Inc(aLast);
	end;
		
end;
procedure CheckMinimumArmy(var aData : Integer; aMinimum : Integer);
begin
	If aData = 0 then
		aData := aMinimum;
end;


procedure GetGroups;
var I, J : Integer;
begin

	CheckMinimumArmy(CampaignData.Mission19.Soldiers[19], 12);
	CheckMinimumArmy(CampaignData.Mission19.Soldiers[20], 12);
	CheckMinimumArmy(CampaignData.Mission19.Soldiers[17], 48);
	CheckMinimumArmy(CampaignData.Mission19.Soldiers[21], 24);
	CheckMinimumArmy(CampaignData.Mission19.Soldiers[22], 15);
	CheckMinimumArmy(CampaignData.Mission19.Soldiers[15], 10);
	//CheckMinimumArmy(CampaignData.Mission19.Soldiers[29], 8);//skip ballistas for now
	
	
	CheckMinimumArmy(CampaignData.Mission20.Soldiers[16], 24);
	CheckMinimumArmy(CampaignData.Mission20.Soldiers[17], 6);
	CheckMinimumArmy(CampaignData.Mission20.Soldiers[18], 18);
	CheckMinimumArmy(CampaignData.Mission20.Soldiers[21], 12);
	CheckMinimumArmy(CampaignData.Mission20.Soldiers[22], 36);
	CheckMinimumArmy(CampaignData.Mission20.Soldiers[15], 60);
	CheckMinimumArmy(CampaignData.Mission20.Soldiers[78], 120);
	CheckMinimumArmy(CampaignData.Mission20.Soldiers[58], 3);
	CheckMinimumArmy(CampaignData.Mission20.Soldiers[81], 4);
	
	CheckMinimumArmy(CampaignData.Mission21.Soldiers[49], 24);
	CheckMinimumArmy(CampaignData.Mission21.Soldiers[50], 24);	

	J := 0;
	for I := 14 to 81 do 	
		If CampaignData.Mission19.Soldiers[I] > 0 then
			AddGroup(0, J, I, CampaignData.Mission19.Soldiers[I]);
			
	for I := 14 to 81 do 	
		If CampaignData.Mission20.Soldiers[I] > 0 then
			AddGroup(1, J, I, CampaignData.Mission20.Soldiers[I]);//drein army
			
	for I := 14 to 81 do 	
		If CampaignData.Mission21.Soldiers[I] > 0 then
			AddGroup(0, J, I, CampaignData.Mission21.Soldiers[I]);
			
	AddGroup(2, J, 50, 85);
	AddGroup(2, J, 18, 30);
	AddGroup(2, J, 52, 15);
	
	A.AIDefencePositionRemoveAll(0);
end;

procedure OnTick;
var GT : Cardinal;
begin
	GT := S.GameTime;	
end;

procedure OnMissionStart;
begin	
	Hero_AddFromLoc(39, 49, 6, 'Malcolm', false);
	Hero_AddFromLoc(39, 51, 14, 'Attylia', false);
	Hero_AddFromLoc(39, 58, 15, 'Alan', true);
	Hero_AddFromLoc(39, 62, 13, 'Drein', true);
	
	Hero_SetStats('Malcolm', 6, 90, 40, 5, 28, 7, 2, 40);
	Hero_SetStats('Attylia', 5, 340, 80, 3, 26, 9, 5, 1);
	Hero_SetStats('Alan', 8, 120, 10, 6, 28, 8, 3, 4);
	Hero_SetStats('Drein', 9, 305, 200, 7, 30, 7, 2, 10);
	
	A.UnitHPSetInvulnerable(Hero_IdByName('Alan'), true);
	A.UnitHPSetInvulnerable(Hero_IdByName('Drein'), true);
	
	gPanelsRefreshRate := 5;//this must be here
	
	OverlayDialogSetup;	
	Dialog_SetStartTime(1);
	Dialog_Loc(39, 55);
	Dialog_Add(50, 35, Hero_IDByName('Malcolm') );
	Dialog_Add(51, 30, Hero_IDByName('Attylia') );
	
	GetGroups;
end;


procedure OnPlayerVictory(aPlayer : Integer);
var I : Integer;
begin	
	for I := 14 to 81 do 
		If not (I in [30, 31, 32, 33, 34, 35, 36, 37, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]) then
		begin
			CampaignData.Mission28Malcolm.Soldiers[I] := S.StatUnitTypeCount(PLAYER, I);
			CampaignData.Mission28Drein.Soldiers[I] := S.StatUnitTypeCount(1, I);
			CampaignData.Mission28Alan.Soldiers[I] := S.StatUnitTypeCount(2, I);
		end;
end;