const	
	PLAYER = 0;
{.$DEFINE DebugDialog}
{.$DEFINE DebugHero}
{$DEFINE DebugGameSpeed}
{$I KD_CustomPanel.script} //custom panel 
{$I KD_Dialog.script}
{$I KD_Heroes.script}
{.$I KD_SaveDefPos.script}
{.$I KD_GatherResources.script}
{$I KD_GatherArmy.script}
{.$I KD_Events.script}


	
var DialogEnd : Integer;
	Guest : record//guest, not Guest
		ID, GroupID, AttackTime : integer;
		KineticPos : TKMPoint;
		KineticTime, KineticRadius : Integer;
		Spawned : Cardinal;
	end;

Procedure KillNotAllied(aUnit : Integer);
begin
	If aUnit <= 0 then 
		Exit;
	If S.UnitOwner(aUnit) in [1] then 
		Exit;
	A.UnitKill(aUnit, false);
	
end;

procedure DamageHouse(aHouse, aAmount : Integer);
begin
	If aHouse <= 0 then 
		Exit;
	A.HouseAddDamage(aHouse, aAmount)
end;

procedure DoKineticExplosion;
var aX ,aY, aRadius : integer;
begin
	aRadius := Guest.KineticRadius;	
				
	for aX := Guest.KineticPos.X - aRadius to Guest.KineticPos.X + aRadius do
		for aY := Guest.KineticPos.Y - aRadius to Guest.KineticPos.Y + aRadius do
		begin
			KillNotAllied(S.UnitAt(aX,aY));
			DamageHouse(S.HouseAt(aX,aY), 50);
		end;

end;

procedure KineticExplosion(aPos : TKMPoint);
var aX ,aY, aRadius : integer;
	aRandom : Single;
begin
	aRandom := S.KamRandom; 
	If aRandom < 0.05 then 
		aRadius := 4
	else
	If aRandom < 0.3 then 
		aRadius := 2
	else
		aRadius := 1;
		
	case aRadius of 
		1: A.SpecialAnimAddFront(aPos.X, aPos.Y, [1501, 1502, 1503, 1504, 1505], 1);
		2: A.SpecialAnimAddFront(aPos.X, aPos.Y, [1496, 1497, 1498, 1499, 1500], 1);
		4: A.SpecialAnimAddFront(aPos.X, aPos.Y, [1491, 1492, 1493, 1494, 1495], 1);		
	end;
	
	Guest.KineticPos := aPos;
	Guest.KineticTime := S.GameTime;	
	Guest.KineticRadius := aRadius;		
end;

Procedure OnUnitHit(aUnit,aAttacker : integer);
begin
	If aAttacker = Guest.ID then 
	begin
		if S.GameTime >= Guest.KineticTime then
			KineticExplosion(S.UnitPosition({Guest.ID}aUnit));
	end;
end;

procedure OnHouseDamaged(aHouse, aAttacker : Integer);
begin
	If aAttacker = Guest.ID then 
	begin
		A.HouseAddDamage(aHouse, 400);
		//A.SpecialAnimAddFront(S.UnitPositionX(aAttacker), S.UnitPositionY(aAttacker), [1491, 1492, 1493, 1494, 1495], 1);		
		KineticExplosion(S.UnitPosition(aAttacker));
	end;
end;



procedure ShowMsg(I : Integer);
begin
	A.ShowMsg(PLAYER, IntToMsg(I));
end;

procedure OnTick;
var GT : Cardinal;
begin
	GT := S.GameTime;
	If (Guest.Spawned = 0) then
		If HasArmy then 
		begin
			Guest.Spawned := GT;
			Guest.GroupID := A.GiveGroup(1, 26, 131, 94, 4, 1, 1);
			Guest.ID := S.GroupMember(Guest.GroupID, 0);
			A.GroupMakeHero(Guest.GroupID, true);
			Unit_SetStats(Guest.ID, 200, 1200, 1000, 100, 26, 8, 10, 10);
			A.UnitHPSetInvulnerable(Guest.ID, true);
		end;
		
		
	If Guest.Spawned > 0 then
	begin
		If GT = Guest.Spawned + 600 then 
		begin
			A.GiveGroup(1, 16, 13, 94, 0, 15, 5);
			A.GiveGroup(1, 16, 20, 94, 0, 15, 5);
			A.GiveGroup(1, 16, 125, 90, 0, 15, 5);
		end;
		If GT = Guest.Spawned + 1200 then 
		begin
			A.GiveGroup(1, 16, 13, 94, 0, 15, 5);
			A.GiveGroup(1, 16, 20, 94, 0, 15, 5);
			A.GiveGroup(1, 16, 125, 90, 0, 15, 5);
		end;
		If GT = Guest.Spawned + 1800 then 
		begin
			A.GiveGroup(1, 16, 13, 94, 0, 25, 5);
			A.GiveGroup(1, 16, 20, 94, 0, 25, 5);
			A.GiveGroup(1, 16, 125, 90, 0, 25, 5);
		end;
		If GT = Guest.Spawned + 2400 then 
			A.PlayerWin([0], true);
		
	end;
	
	
	
	If GT = 10 then 
		ShowMsg(50);
	//Guest effect
	If Guest.KineticTime > 0 then 
		If GT = Guest.KineticTime + 4 - (Guest.KineticRadius div 2) then 
			DoKineticExplosion;
end;

procedure OnMissionStart;
begin
	gDialog.Player := PLAYER;
	gArmy.Player := PLAYER;
					
	gPanelsRefreshRate := 5;//this must be here	
	
	Army_Add(utFlailFighter, 36);
	Army_Add(utCrossbowman, 80);
	Army_Add(utSwordFighter, 36);
	Army_Add(utTrainedWolf, 8);
end;