const	
	PLAYER = 1;
{.$DEFINE DebugDialog}
{.$DEFINE DebugHero}
{$DEFINE DebugGameSpeed}
{$I KD_CustomPanel.script} //custom panel 
{$I KD_Dialog.script}
{$I KD_Heroes.script}
{.$I KD_SaveDefPos.script}
{.$I KD_GatherResources.script}
{$I KD_GatherArmy.script}
{.$I KD_Events.script}
	
var DialogEnd, Servant : Integer;


procedure ShowMsg(I : Integer);
begin
	A.ShowMsg(PLAYER, IntToMsg(I));
end;

procedure OnTick;
var GT : Cardinal;
begin
	GT := S.GameTime;
	
	If HasArmy then 
		A.PlayerWin([PLAYER], true);
	If GT = DialogEnd then 
		ShowMsg(54);
end;

procedure OnMissionStart;
begin
	gDialog.Player := PLAYER;
	gArmy.Player := PLAYER;
	Servant := S.UnitAt(80, 79);
	
	Hero_AddFromLoc(85, 89, 13, 'Drein', false);
	Hero_SetStats('Drein', 11, 305, 200, 12, 30, 7, 2, 10);	
	
	OverlayDialogSetup;	
	Dialog_SetStartTime(1);
	Dialog_Loc(84, 89);
	Dialog_AddEmpty(100);
	Dialog_Add(50, 30, Servant);
	Dialog_Add(51, 30, Hero_IDByName('Drein') );
	Dialog_Add(52, 30, Servant);
	Dialog_Add(53, 30, Hero_IDByName('Drein') );

					
	DialogEnd := Dialog_EndTime;
	gPanelsRefreshRate := 5;//this must be here
	
	
	Army_Add(utSwordFighter, 24);
	Army_Add(utBowman, 6);
	Army_Add(utCrossbowman, 18);
	Army_Add(utScout, 12);
	Army_Add(utKnight, 36);
	Army_Add(utAxeFighter, 60);
	Army_Add(utBerserker, 120);
	Army_Add(utMedic, 3);
	Army_Add(utAlchemist, 4);
end;

procedure OnPlayerVictory(aPlayer : Integer);
var I : Integer;
begin	
	for I := 14 to 81 do 
		If not (I in [30, 31, 32, 33, 34, 35, 36, 37, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72]) then
		CampaignData.Mission20.Soldiers[I] := S.StatUnitTypeCount(PLAYER, I);
end;